- name: Install latest Cockpit
  yum:
    name: 
      - storaged
      - cockpit
      - cockpit-storaged
      - pcp
    state: latest
- name: Enable and start cockpit socket
  service:
    name: cockpit.socket
    state: started
    enabled: true
