- name: Create directory conf.d
  file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add http nginx configuration
  template: src=nginx.http.conf.j2 dest=/etc/nginx/conf.d/{{ domain_name }}.http.conf owner=nginx group=nginx mode=0644
  notify: restart nginx
