- name: Install curl socat openssl crontabs
  yum:
    name: 
      - curl
      - socat
      - crontabs
      - openssl
    state: latest
- name: Determine whether acme.sh is installed
  stat:
    path: /root/.acme.sh
  register: find_acmesh
- name: Install the latest acme.sh if not installed
  shell:
    cmd: curl https://get.acme.sh | sh
  args:
    warn: no
  when: find_acmesh.stat.exists == false
