- name: Install certbot
  yum:
    name: python3-certbot-nginx
    state: present

- name: Create and Install Cert Using nginx Plugin
  command: "certbot --nginx -d  {{ domain_name }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --redirect"

- name: Set Letsencrypt Cronjob for Certificate Auto Renewal
  cron: name=letsencrypt_renewal special_time=monthly job="/usr/bin/certbot renew"
