- name: Create directory for certs
  file:
    path: /etc/pki/nginx/{{ domain_name }}
    state: directory
    mode: '0755'
- name: Issue cert
  shell:
    cmd: /root/.acme.sh/acme.sh --issue -d {{ domain_name }} --nginx
  register: out
  failed_when: out.rc != 0 and 'Skip' not in out.stdout
- name: Install cert
  shell: /root/.acme.sh/acme.sh --install-cert -d {{ domain_name }} --key-file /etc/pki/nginx/{{ domain_name }}/key.pem --fullchain-file /etc/pki/nginx/{{ domain_name }}/cert.pem
