---
- name: Install nginx with ssl and php-fpm
  hosts: webservers
  remote_user: root
  roles:
    - nginx_with_ssl
    - php_fpm
    - cockpit
    - h5ai
    - mariadb
    - qbittorrent
  pre_tasks:
    - name: check if the system is yum-based
      debug:
        msg: "Host {{ inventory_hostname}} is yum-based"
      failed_when: "ansible_pkg_mgr != 'dnf'"
      any_errors_fatal: true
