- name: install mariadb packages
  yum:
    name: '{{ item }}'
    state: present
  loop:
  - mariadb-server, mariadb
  - php-mysqlnd, python3-PyMySQL
- name: start and enable mariadb service
  service:
    name: mariadb
    state: started
    enabled: true
