- name: Change php user and group to nginx
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: '^{{ item.apache }}'
    line: '{{ item.nginx }}'
  loop:
  - user:
    apache: "user ="
    nginx: "user = nginx"
  - group: 
    apache: "group ="
    nginx: "group = nginx"
  notify: "restart web services"
- name: Add php nginx config file
  template:
    src: php.conf.j2
    dest: /etc/nginx/default.d/php.conf
  notify: "restart web services"
