- name: Install latest php and php-fpm
  yum:
    name: 
      - php-fpm
      - php
    state: latest
- name: Start and Enable php-fpm
  service:
    name: php-fpm
    state: started
    enabled: true
