- name: Change ownership of /var/lib/php
  file:
    path: /var/lib/php
    owner: nginx
    group: nginx
    mode: 0744
    recurse: yes
- name: Change ownership of webroot
  file:
    path: /usr/share/nginx/html
    owner: nginx
    group: nginx
    mode: 0744
    recurse: yes
