- name: Add a non-sudoable user {{ mariadb_username }}
  user:
    name: "{{ mariadb_username }}"
    password: "{{ mariadb_pwd | password_hash('sha512') }}"
    state: present 
- name: change db password of user {{ mariadb_username }}
  mysql_user:
    name: "{{ mariadb_username }}"
    password: "{{ mariadb_pwd }}"
    priv: '*.*:ALL'
  notify: restart mariadb
