- name: Add a non-sudoable user {{ qbittorrent_username }}
  user:
    name: "{{ qbittorrent_username }}"
    password: "{{ qbittorrent_pwd | password_hash('sha512') }}"
    shell: "/sbin/nologin"
    state: present 
